name: unit test
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -name: Setup DotNet
       uses: actions/setup-dotnet@v3
      -name: Install dependencies
       run: dotnet restore
      -name: Test with dotnet
       run: dotnet test 
